// <auto-generated />
using System;
using Kasa.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kasa.Api.Migrations
{
    [DbContext(typeof(KasaDbContext))]
    [Migration("20260702112526_AddFleetSnapshot")]
    partial class AddFleetSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Kasa.Api.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type", "IsActive");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Kiralama",
                            SortOrder = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Eksik Yakıt Tahsilatı",
                            SortOrder = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Ekstra Servis",
                            SortOrder = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Kiralama Uzatma",
                            SortOrder = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Hasar",
                            SortOrder = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Diğer",
                            SortOrder = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Servis Bakım",
                            SortOrder = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Yakıt Alım",
                            SortOrder = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Su Alım",
                            SortOrder = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Nakliye",
                            SortOrder = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Kira",
                            SortOrder = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Elektrik",
                            SortOrder = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Maaş",
                            SortOrder = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Diğer",
                            SortOrder = 8,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Kasa.Api.Data.FleetSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrokenBikes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("RentedBikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBikes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("FleetSnapshots", t =>
                        {
                            t.HasCheckConstraint("CK_FleetSnapshot_Capacity", "\"BrokenBikes\" + \"RentedBikes\" <= \"TotalBikes\"");

                            t.HasCheckConstraint("CK_FleetSnapshot_NonNegative", "\"TotalBikes\" >= 0 AND \"BrokenBikes\" >= 0 AND \"RentedBikes\" >= 0");
                        });
                });

            modelBuilder.Entity("Kasa.Api.Data.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "PosFeeRate",
                            Value = "0.035"
                        },
                        new
                        {
                            Key = "Partner1Name",
                            Value = "Amornrat Thanmaen"
                        },
                        new
                        {
                            Key = "Partner1Share",
                            Value = "0.90"
                        },
                        new
                        {
                            Key = "Partner2Name",
                            Value = "Thanchanok Sabancıoğlu"
                        },
                        new
                        {
                            Key = "Partner2Share",
                            Value = "0.10"
                        });
                });

            modelBuilder.Entity("Kasa.Api.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountSatang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_AmountSatang", "\"AmountSatang\" > 0");
                        });
                });

            modelBuilder.Entity("Kasa.Api.Data.Transaction", b =>
                {
                    b.HasOne("Kasa.Api.Data.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
